DjangoProjects/mysite-win/blog/urls.py
#from django.conf.urls.defaults import *
from django.conf.urls import *
import blog.views
urlpatterns = [
    url(r'^$', blog.views.archive,),
    url(r'^create/', blog.views.create_blogpost),
    url(r'^search/$', blog.views.search, name='search'),

]

DjangoProjects/mysite-win/mysite/urls.py
from django.conf.urls import *
from django.contrib import admin

admin.autodiscover()
#urlpatterns = [
#    url(r'^admin/', admin.site.urls),
#]
urlpatterns = [
    url(r'^blog/',include('blog.urls')),
    url(r'^search/',include('blog.urls')),
    url(r'^admin/',admin.site.urls),
]

DjangoProjects/mysite-win/blog/models.py
from django.db import models
from django import forms
# Create your models here.

class BlogPost(models.Model):
    title = models.CharField(max_length=150)
    body = models.TextField()
    timestamp = models.DateTimeField()

class BlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        exclude = ('timestamp',)

DjangoProjects/mysite-win/blog/views.py
#coding:utf-8
from django.shortcuts import render
# Create your views here.
from django.http import HttpResponse
from django.template import loader,Context
from blog.models import BlogPost
from blog.models import BlogPostForm

from django.shortcuts import render_to_response
from django.template import RequestContext

#create_blogpost
from datetime import datetime
from django.http import HttpResponseRedirect

from django.views.decorators.csrf import csrf_exempt

@csrf_exempt
def archive(request):
    posts = BlogPost.objects.all().order_by('-timestamp')[:5]
    t = loader.get_template("archive.html")
##  c = Context({'posts': posts})
    html = t.render({'posts': posts, 'form': BlogPostForm()})
    return HttpResponse(html,RequestContext(request))
#   return render_to_response('archive.html', {'posts': posts, 'form': BlogPostForm()}, RequestContext(request))

@csrf_exempt
def create_blogpost(request):
    if request.method == 'POST':

#      BlogPost(
#          title = request.POST.get('title'),
#          body = request.POST.get('body'),
#          timestamp = datetime.now(),
#      ).save()
       form = BlogPostForm(request.POST)
       if form.is_valid():
           post = form.save(commit=False)
           post.timestamp = datetime.now()
           post.save()
    return HttpResponseRedirect('/blog/')

@csrf_exempt
def search(request):
    q = request.GET.get('q')
    error_msg = ''
    if not q:
        error_msg = '请输入关键词'
        return render(request, 'index.html', {'error_msg': error_msg})

    post_list = BlogPost.objects.filter(title__icontains=q)
    return render(request, 'index.html', {'error_msg': error_msg, 'post_list': post_list})

DjangoProjects/mysite-win/blog/templates/archive.html
<!-- archive.html -->
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<div id="header-search-box">
<form role="search" method="get" id="searchform" action="search">
  {% csrf_token %}
  <input type="search" name="q" placeholder="Search" required>
  <button type="submit">SEARCH</button>
</form>
    </div>
<hr>

{% for post in posts %}
<h2>{{ post.title }}</h2>
<p>{{ post.timestamp }}</p>
<p>{{ post.body }}</p>
<hr>
{% endfor %}
<hr>

<form action="/blog/create/" method="post">
    {% csrf_token %}
     Ipaddr:
     <input type=text name=title><br>
     Details:
    <textarea name="body" cols="68" rows="3" required="" id="id_body"></textarea><br>
<!--    <textarea name=body rows=3 cols=60></textarea><br>
       <table>{{ form }}</table><br> -->
    <input type="submit" value="Submission">
</form>
<hr>

DjangoProjects/mysite-win/blog/templates/index.html
<!-- {% extends 'archive.html' %}
{% block main %} -->
  {% if error_msg %}
    <p>{{ error_msg }}</p>
  {% endif %}

  {% for post in post_list %}
    <div>
        {{ post.title }}
    </div>
  {% empty %}
    <div class="no-post">
        暂时还没有发布的文章！
    </div>
  {% endfor %}
<!--{% endblock main %} -->